version: '3'

services:
  # docker-gen identifies by reading the environment variable ONIONSERVICE_NAME   
  # what services should be added to the list of hidden onion services in torrc
  onionize:
    image: torservers/onionize
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - darkcloud
    restart: always  
    
  # IDS to scan docker images and file shares for malware
  ids:
    image: deepfenceio/yara-hunter:latest
    ulimits:
      core: 1
    networks:
      - whitecloud      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    entrypoint: /home/deepfence/usr/YaRadare
    command: ["-config-path","/home/deepfence/usr", "-standalone-http-port", "8011"]
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        
  # customized Kali Linux as SOC
  soc:
    image: darkcloud-soc
    build: ./nextcloud/soc
    stdin_open: true
    tty: true    
    networks:
      - whitecloud  
    restart: always   
    
  # hidden nextcloud service
  nextcloud:
    image: nextcloud:apache
    environment:
      - ONIONSERVICE_NAME=nextcloud
    networks:
      - darkcloud
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud/volumes/config:/var/www/html/config
      - ./nextcloud/volumes/custom_apps:/var/www/html/custom_apps
      - ./nextcloud/volumes/data:/var/www/html/data
      - ./nextcloud/volumes/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    
  # nextcloud database
  db:
    image: mariadb
    networks:
      - darkcloud
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
    
volumes:
  nextcloud:
  db:
  
networks:
  darkcloud:
    driver: bridge
  whitecloud:
    driver: bridge